feat: update tlp to 1.7.0-1

diff --git a/tlp-run-on.in b/tlp-run-on.in
--- a/tlp-run-on.in
+++ b/tlp-run-on.in
@@ -1,7 +1,7 @@
 #!/bin/sh
 # tlp - run commands depending on power source
 #
-# Copyright (c) 2023 Thomas Koch <linrunner at gmx.net> and others.
+# Copyright (c) 2024 Thomas Koch <linrunner at gmx.net> and others.
 # SPDX-License-Identifier: GPL-2.0-or-later
 
 # --- Source libraries
@@ -17,11 +17,11 @@ self=${0##*/}
 
 cmd=$1
 if [ -z "$cmd" ]; then
-    echo "Usage: $self command [arg(s)]" 1>&2
+    cecho "Usage: $self command [arg(s)]" 1>&2
     exit 1
 fi
 if ! cmd_exists "$cmd"; then
-    echo "Error: \"$cmd\" not found." 1>&2
+    cecho "Error: \"$cmd\" not found." 1>&2
     exit 2
 fi
 shift
@@ -40,7 +40,7 @@ case $self in
         ;;
 
     *)
-        echo "Error: unknown mode $self." 1>&2
+        cecho "Error: unknown mode $self." 1>&2
         exit 1
         ;;
 esac
